# Generated by Django 5.1.1 on 2024-10-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
