# Generated by Django 5.1.1 on 2024-10-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogs_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='photos',
            new_name='image',
        ),
    ]
