# Generated by Django 5.1.1 on 2024-10-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogs_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='image',
            new_name='images',
        ),
    ]
