# Generated by Django 5.1.1 on 2024-10-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_image_blogs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
